mod chat;
mod clipboard_utils;
mod config;
mod constants;
mod daemon;
mod editing;
mod git_ops;
mod git_panels;
mod help;
mod llm;
mod matching;
mod minimap;
mod palette;
mod split_view;
mod state;
mod status_bar;
mod toolbar;
mod types;
pub use state::MergeApp;
pub use palette::pal;